# Generated by Django 2.1.5 on 2019-01-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='customers',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='date_publication',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
    ]
