# Generated by Django 2.1.5 on 2019-01-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_auto_20190116_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='unique_views',
        ),
    ]
